# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dilawar/Work/GITHUB/sound

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dilawar/Work/GITHUB/sound

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dilawar/Work/GITHUB/sound/CMakeFiles /home/dilawar/Work/GITHUB/sound/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dilawar/Work/GITHUB/sound/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DSPFilters

# Build rule for target.
DSPFilters: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DSPFilters
.PHONY : DSPFilters

# fast build rule for target.
DSPFilters/fast:
	$(MAKE) -f CMakeFiles/DSPFilters.dir/build.make CMakeFiles/DSPFilters.dir/build
.PHONY : DSPFilters/fast

#=============================================================================
# Target rules for targets named songbird

# Build rule for target.
songbird: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 songbird
.PHONY : songbird

# fast build rule for target.
songbird/fast:
	$(MAKE) -f CMakeFiles/songbird.dir/build.make CMakeFiles/songbird.dir/build
.PHONY : songbird/fast

#=============================================================================
# Target rules for targets named aiff

# Build rule for target.
aiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aiff
.PHONY : aiff

# fast build rule for target.
aiff/fast:
	$(MAKE) -f aiff/CMakeFiles/aiff.dir/build.make aiff/CMakeFiles/aiff.dir/build
.PHONY : aiff/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f wave/CMakeFiles/wave.dir/build.make wave/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named dsp

# Build rule for target.
dsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dsp
.PHONY : dsp

# fast build rule for target.
dsp/fast:
	$(MAKE) -f dsp/CMakeFiles/dsp.dir/build.make dsp/CMakeFiles/dsp.dir/build
.PHONY : dsp/fast

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/songbird.dir/build.make CMakeFiles/songbird.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/songbird.dir/build.make CMakeFiles/songbird.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/songbird.dir/build.make CMakeFiles/songbird.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... DSPFilters"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... songbird"
	@echo "... aiff"
	@echo "... wave"
	@echo "... dsp"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

